### ISSUE TITLE
Ikea change

### ISSUE THREAD

**Issue by Hydro8** [Com-AugustCellars/CoAP-CSharp#42]
Hi
I know that you're not supporting ikea tradfri especially, but I didn't find someone to help me.

Apparently Ikea change the way to communicate with the gateway : https://community.openhab.org/t/ikea-tradfri-gateway/26135/148?u=kai

Do you know something about this ? Do you know how to connect right now ?

I try to see how python code works now but I don't find any solution.

Thank for your help !

**Comment by jimsch** [comment]
Look at #41 it covers what you need.

**Comment by Hydro8** [comment]
Sadly I don't understand everything, I don't use put on my code.

userKey.Add(CoseKeyKeys.KeyType,GeneralValues.KeyType_Octet);
userKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes(PackageHost.GetSettingValue<string>("GatewayKey"))));

client = new CoapClient(new Uri($"coaps://" + PackageHost.GetSettingValue<string>("GatewayIP") + "/.well-known/core"));

ep = new DTLSClientEndPoint(userKey);
client.EndPoint = ep;
ep.Start();
IEnumerable<WebLink> items = client.Discover();

foreach (var node in items)  {...}

The other person doesn't use Discover if I'm not wrong.

**Comment by Hydro8** [comment]
Ok so I must add c# version of: 'authKey.Add(COSE.CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes("Client_identity")))
Client_identity is a random string or something particular ?

**Comment by bmachuletz** [comment]
Hi,I've heard about the change in the API and tried to code against. When I add the "CoseKeyKeys.KeyIdentifier" my code stops working. My current gateway version is 1.2.42 (the Tradfri-App shows me that this is the newest and best version ever).To answer your question: This should be a "random" string like your application name for instance.Hydro8 <notifications@github.com> hat am 23. November 2017 um 10:01 geschrieben:Ok so I must add c# version of: 'authKey.Add(COSE.CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes("Client_identity"))) Client_identity is a random string or something particular ?—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Hydro8** [comment]
ok I tried to add this line but something else must interrupt the identification 
 
   `userKey.Add(CoseKeyKeys.KeyType, GeneralValues.KeyType_Octet);
            userKey.Add(CoseKeyParameterKeys.Octet_k, CBORObject.FromObject(Encoding.UTF8.GetBytes(PackageHost.GetSettingValue<string>("GatewayKey"))));
            userKey.Add(CoseKeyKeys.KeyIdentifier, CBORObject.FromObject(System.Text.Encoding.UTF8.GetBytes("Constellation")));
            client = new CoapClient(new Uri($"coaps://" + PackageHost.GetSettingValue<string>("GatewayIP") + "/.well-known/core"));

            ep = new DTLSClientEndPoint(userKey);

            client.EndPoint = ep;
            ep.Start();`
