### ISSUE TITLE
API for handling ACK message sent from observer

### ISSUE THREAD

**Issue by keithpurr** [Com-AugustCellars/CoAP-CSharp#44]
Hi,

I have a client observing certain resource on a server, for evaluation purpose, I am trying to measure the latency between a server sending out a CON notification to a client & the server receiving the according ACK message from the client.

My question is, I can’t seem to find an API/ Event Handler to call for when the ACK message is received on server side, could you please shed some light on this?

**Comment by jimsch** [comment]
You are looking for the RTT property on the response.

**Comment by jimsch** [comment]
Sorry - that is the round trip time.  There is no property in the API to measure the one way transmission time.  The best you can do is round trip.  Doing the other would require carrying the transmission time as part of the packet which does not exist.  The other way to do it is to use something like WireShark to look at all of the traffic on the network, but even that is going to have network delays built into the system. 

Part of the problem is always going to be a time sync between both parties which is going to mess up the measurement.  Just use the round trip property as a good proxy.

**Comment by keithpurr** [comment]
Thank you so much for the timely and thorough comment (mine on the other hand is super late...), I went with both WireShark & RTT in the end.
